/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigBaseTab: typeof import('./src/components/config/base/ConfigBaseTab.vue')['default']
    ConfigColumn: typeof import('./src/components/config/ConfigColumn.vue')['default']
    ConfigFile: typeof import('./src/components/config/ConfigFile.vue')['default']
    ConfigFiles: typeof import('./src/components/config/ConfigFiles.vue')['default']
    ConfigInput: typeof import('./src/components/config/ConfigInput.vue')['default']
    ConfigViewport: typeof import('./src/components/config/ConfigViewport.vue')['default']
    copy: typeof import('./src/components/editor/EditorConfigBlock copy.vue')['default']
    EditorBlock: typeof import('./src/components/editor/EditorBlock.vue')['default']
    EditorBlockDrag: typeof import('./src/components/editor/EditorBlockDrag.vue')['default']
    EditorConfig: typeof import('./src/components/editor/EditorConfig.vue')['default']
    EditorConfigBlock: typeof import('./src/components/editor/EditorConfigBlock.vue')['default']
    EditorConfigPage: typeof import('./src/components/editor/EditorConfigPage.vue')['default']
    EditorConfigRender: typeof import('./src/components/editor/EditorConfigRender.vue')['default']
    EditorHeader: typeof import('./src/components/editor/EditorHeader.vue')['default']
    EditorRender: typeof import('./src/components/editor/EditorRender.vue')['default']
    EditorRenderDrag: typeof import('./src/components/editor/EditorRenderDrag.vue')['default']
    EditorRenderHover: typeof import('./src/components/editor/EditorRenderHover.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('./src/components/base/VIcon.vue')['default']
    VIconTooltip: typeof import('./src/components/base/VIconTooltip.vue')['default']
    Vselect: typeof import('./src/components/base/Vselect.vue')['default']
    VSelect: typeof import('./src/components/base/VSelect.vue')['default']
  }
}
